import type { HistoryEntry } from "./executive-store";

export function exportHistoryToPptx(history: HistoryEntry[]) {
  const curriculum = history.filter((h) => h.type === "curriculum");
  const students = history.filter((h) => h.type === "student");
  const faculty = history.filter((h) => h.type === "faculty");
  const avgScore = history.length ? Math.round(history.reduce((s, h) => s + h.healthScore, 0) / history.length) : 0;

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8" /><title>Executive Report — AI Curriculum Analyzer</title>
<style>
  @page { size: landscape; margin: 40px; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color: #1F2937; margin: 0; padding: 0; }
  .slide { page-break-after: always; min-height: 90vh; padding: 60px; box-sizing: border-box; }
  .slide:last-child { page-break-after: avoid; }
  .title-slide { background: linear-gradient(135deg, #0F2557, #1E3A8A); color: white; display: flex; flex-direction: column; justify-content: center; }
  .title-slide h1 { font-size: 42px; margin: 0; }
  .title-slide p { font-size: 18px; color: #93C5FD; margin-top: 12px; }
  .title-slide .meta { font-size: 14px; color: #6B7280; margin-top: 30px; }
  h2 { color: #0F2557; font-size: 28px; border-bottom: 3px solid #10B981; padding-bottom: 8px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-top: 30px; }
  .stat { background: #F5F7FA; border-radius: 12px; padding: 24px; text-align: center; }
  .stat .value { font-size: 36px; font-weight: 800; color: #0F2557; }
  .stat .label { font-size: 13px; color: #6B7280; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin-top: 24px; font-size: 14px; }
  th { background: #0F2557; color: white; padding: 10px 14px; text-align: left; }
  td { padding: 10px 14px; border-bottom: 1px solid #E5E7EB; }
  tr:nth-child(even) { background: #F9FAFB; }
  .footer-slide { background: #F5F7FA; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; }
  .footer-slide h2 { border: none; color: #0F2557; }
  @media print { .slide { min-height: auto; } }
</style></head><body>
<div class="slide title-slide">
  <h1>AI Curriculum Analyzer</h1>
  <p>Executive Summary Report</p>
  <div class="meta">${history.length} Analyses · Generated ${new Date().toLocaleDateString()}</div>
</div>

<div class="slide">
  <h2>Summary Statistics</h2>
  <div class="stats">
    <div class="stat"><div class="value">${history.length}</div><div class="label">Total Analyses</div></div>
    <div class="stat"><div class="value">${avgScore}</div><div class="label">Avg Health Score</div></div>
    <div class="stat"><div class="value">${Math.max(...history.map((h) => h.healthScore), 0)}</div><div class="label">Highest Score</div></div>
    <div class="stat"><div class="value">${Math.min(...history.map((h) => h.healthScore), 0)}</div><div class="label">Lowest Score</div></div>
  </div>
  <div class="stats" style="grid-template-columns: repeat(3, 1fr); margin-top: 20px;">
    <div class="stat"><div class="value">${curriculum.length}</div><div class="label">Curriculum Analyses</div></div>
    <div class="stat"><div class="value">${students.length}</div><div class="label">Student Analyses</div></div>
    <div class="stat"><div class="value">${faculty.length}</div><div class="label">Faculty Analyses</div></div>
  </div>
</div>

<div class="slide">
  <h2>Recent Analyses</h2>
  <table>
    <tr><th>Type</th><th>Title</th><th>Score</th><th>Label</th><th>Top Strength</th><th>Date</th></tr>
    ${history.slice(0, 15).map((h) => `<tr>
      <td>${h.type.charAt(0).toUpperCase() + h.type.slice(1)}</td>
      <td>${h.title}</td>
      <td><strong>${h.healthScore}</strong></td>
      <td>${h.healthLabel}</td>
      <td>${h.topStrength}</td>
      <td>${new Date(h.analyzedAt).toLocaleDateString()}</td>
    </tr>`).join("")}
  </table>
</div>

<div class="slide footer-slide">
  <h2>Generated by AI Curriculum Analyzer</h2>
  <p style="color: #6B7280; font-size: 14px; margin-top: 8px;">Powered by Claude AI · Real-time analysis of curricula, student profiles, and faculty portfolios</p>
  <p style="color: #9CA3AF; font-size: 12px; margin-top: 20px;">${new Date().toLocaleString()}</p>
</div>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups to export your report.");
    return;
  }
  w.document.write(html);
  w.document.close();
  w.document.title = "Executive Report — AI Curriculum Analyzer";
  setTimeout(() => w.print(), 500);
}
